### ISSUE TITLE
"Can't find variable: Buffer" while successful login on react native

### ISSUE THREAD

**Issue by TyshkevichSergey** [layerhq/layer-websdk#158]
I'm currently trying to implement websdk on react native app. And get this issue after successful login.

![2ab6026864](https://user-images.githubusercontent.com/9352343/27335738-3b6a9b86-55d6-11e7-99d8-b684c0e59cb8.jpg)

It seems this problem related with decode function of base64.js.
This problem also present inside sample project with web sdk for react native.
Any help is appreciated. Thanks.

**Comment by michaelkantor** [comment]
Thanks for the report; will see if I can replicate this tomorrow.

**Comment by michaelkantor** [comment]
Geesh; our react native dev is off to get married... I'm not even getting past:

ERROR in ./~/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Error: Cannot resolve module 'ViewPropTypes' in /Users/michaelkantor/Documents/layer-js-sampleapps/examples/websdk-samples/react/node_modules/react-native/Libraries/react-native
 @ ./~/react-native/Libraries/react-native/react-native-implementation.js 115:31-55

when trying to setup the web sample app.  

If you want this looked at sooner, submit a project that builds and runs (prefer web-only).

**Comment by TyshkevichSergey** [comment]
Hi, thanks for quick response. This is link to download my sample 
[https://www.dropbox.com/s/ptrwxcyg6w4wlvg/LayerReactNativeSample.zip?dl=0](url)

This is just sample for react native using layer websdk. I obtained it from quick start sample project.
Just make npm install and it should works on your side.

**Comment by TyshkevichSergey** [comment]
Here is new update about current issue. Problem with "Can't find variable: Buffer" error related to latest releases. I got success by building the project using  "layer-websdk": "3.2.3" and adding  "buffer": "^5.0.6" as dependency.
My suggestion about the error is next - it's related to this change

3.3.1
Replaces base64url decoder with base64url npm package

Also there is trouble with debug mode for react native app. If you using app in debug mode you will get next exception:

`06-21 05:36:01.890 6874-16652/com.layerreactnativesample E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                           Process: com.layerreactnativesample, PID: 6874
                                                                           java.lang.IllegalStateException: Expected a name but was STRING
                                                                               at android.util.JsonReader.nextName(JsonReader.java:390)
                                                                               at com.facebook.react.devsupport.JSDebuggerWebSocketClient.onMessage(JSDebuggerWebSocketClient.java:196)
                                                                               at okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
                                                                               at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
                                                                               at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
                                                                               at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
                                                                               at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
                                                                               at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
                                                                               at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
                                                                               at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
                                                                               at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)`

**Comment by ValentinBlokhin** [comment]
Any way to fix debug issue?

**Comment by michaelkantor** [comment]
Fix is deployed as WebSDK 3.3.3

**Comment by ilonashub** [comment]
@TyshkevichSergey @ValentinBlokhin did you find a fix to the debug issue?
